use_frameworks!

platform :ios, '13.0'

target 'TTNetworking_Example' do
#  pod 'TTNetworking', :path => '../'
#  pod 'TTNetworking/ObjectMapper', :path => '../'
  pod 'TTNetworking/SmartCodable', :path => '../'
  pod 'TTNetworking/Captcha', :path => '../'
  
  pod 'NSObject+Rx'
  
  post_install do |installer|
       installer.generated_projects.each do |project|
         project.targets.each do |target|
             target.build_configurations.each do |config|
                 config.build_settings['CODE_SIGN_IDENTITY'] = ''
              end
         end
       end
       installer.pods_project.build_configurations.each do |config|
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
           end
       installer.pods_project.targets.each do |target|
           target.build_configurations.each do |config|
               config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
           end
       end
   end
	
end
